GHA: 2.3.0

diff --git a/.github/workflows/env-dev--deploy-traefik-ingressroutes.yaml b/.github/workflows/env-dev--deploy-traefik-ingressroutes.yaml
--- a/.github/workflows/env-dev--deploy-traefik-ingressroutes.yaml
+++ b/.github/workflows/env-dev--deploy-traefik-ingressroutes.yaml
@@ -1,11 +1,13 @@
-## .github/workflows/env-dev--installation-sealed-secrets-controller.yaml
-name: Installation Sealed-Secrets Controller to GKE
+## .github/workflows/env-dev--deploy-traefik-ingressroutes.yaml
+name: Deploy Traefik IngressRoutes to GKE
 
 on:
   push:
     branches:
       - never-trigger-this-branch
       # - main
+    paths:
+      - .github/helm-charts/env-dev/traefik-reverse-proxy/traefik/templates/ingressroutes/**
   workflow_dispatch:
     inputs:
       gke_cluster_name:
@@ -34,19 +36,15 @@ env:
   GCP_SERVICE_ACCOUNT: ${{ secrets.COMMIT_HW_GCP_SERVICE_ACCOUNT_PROJECT_B }} 
 
 jobs:
-  installation-sealed-secrets-controller:  
-    name: Install Sealed-Secrets Controller to GKE
+  apply-traefik-ingressroutes:
+    name: Apply Traefik IngressRoutes to GKE
     runs-on: ubuntu-24.04
-    # This explicit binding allows access to the environment-scoped secrets
     environment: commit-dev
 
     # Declare environment variables for the current job
     env:
-      HELM_CHART_VERSION: "2.19.1" # https://bitnami.github.io/sealed-secrets/index.yaml
-      CONTROLLER_VERSION: "0.38.4" # https://github.com/bitnami/sealed-secrets/releases
-      HELM_REPO_NAME: "sealed-secrets"
-      HELM_REPO_URL: "https://bitnami.github.io/sealed-secrets"
-      ERROR_LOG_FILE: "err.log"
+      NAMESPACE: "traefik-reverse-proxy"
+      TRAEFIK_INGRESSROUTES_DIR: .github/helm-charts/env-dev/traefik-reverse-proxy/traefik/templates/ingressroutes
 
     steps:
       # Step 1: Print who triggered this build (whoami)
@@ -67,7 +65,7 @@ jobs:
       - name: Authenticate to Google Cloud via OIDC
         uses: google-github-actions/auth@v3
         with:
-          # Construct the provider string inside the step using standard bash variable notation
+          # GitHub Actions → GCP Workload Identity Federation exchange
           workload_identity_provider: "projects/${{ env.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider"
           service_account: "${{ env.GCP_SERVICE_ACCOUNT }}"
 
@@ -85,38 +83,44 @@ jobs:
           echo "Checking connection to GKE..."
           kubectl get nodes || { echo "❌ ERROR: Cannot connect to GKE cluster"; exit 1; }
 
-      # Step 7: Check and Install Sealed-Secrets Controller via Helm
-      - name: Check and Install Sealed-Secrets Controller via Helm
+      # Step 7: Check Traefik CRDs
+      - name: Check Traefik CRDs
         run: |
-          echo "::group::Checking installed Sealed-Secrets Controller"
-          if kubectl get deploy sealed-secrets -n kube-system >/dev/null 2>&1; then
-            echo "✅ Sealed-Secrets Controller is already installed"
-            exit 0
+          if ! kubectl get crd ingressroutes.traefik.io serverstransports.traefik.io >/dev/null 2>&1; then
+            echo "❌ ERROR: Traefik CRDs are missing! Did you deploy Traefik Helm chart?"
+            exit 1
           fi
-          echo "::endgroup::"
+          echo "✅ Traefik CRDs found."
 
-          echo "⚠️ Sealed-Secrets Controller does not exist."
+     # Step 8: Show diff of IngressRoutes
+      - name: Show diff
+        run: |
+          set -euo pipefail
+          set +e
+          kubectl diff -R -f "${TRAEFIK_INGRESSROUTES_DIR}"
+          DIFF_EXIT_CODE="$?"
+          set -e
 
-          echo "::group::⚠️ Installing Sealed-Secrets Controller via Helm..."
-          helm repo add "${HELM_REPO_NAME}" "${HELM_REPO_URL}"
-          helm repo update
-
-          if ! helm upgrade --install sealed-secrets "${HELM_REPO_NAME}/sealed-secrets" \
-                  --namespace kube-system \
-                  --create-namespace \
-                  --version "${HELM_CHART_VERSION}" \
-                  --set image.tag="${CONTROLLER_VERSION}" 2>"${ERROR_LOG_FILE}"; then
-            if grep -q "Forbidden" "${ERROR_LOG_FILE}"; then
-              echo "❌ ERROR: Cannot install Sealed-Secrets Controller via Helm. Missing RBAC permission!"
-              cat "${ERROR_LOG_FILE}"
-              exit 1
-            else
-              echo "❌ ERROR: Failed to install Sealed-Secrets Controller via Helm due to an unknown error:"
-              cat "${ERROR_LOG_FILE}"
-              exit 1
-            fi
-          else
-            echo "✅ Sealed-Secrets Controller successfully installed via Helm."
+          if [ "${DIFF_EXIT_CODE}" -gt 1 ]; then
+            echo "❌ kubectl diff failed"
+            exit "${DIFF_EXIT_CODE}"
           fi
-          
-          echo "::endgroup::"
+
+      # Step 10: Apply Traefik IngressRoutes
+      - name: Apply IngressRoutes
+        run: |
+          set -euo pipefail
+
+          echo "Applying Traefik IngressRoute manifests..."
+          kubectl apply -R -f "${TRAEFIK_INGRESSROUTES_DIR}" || {
+            echo "❌ Failed to apply IngressRoutes"
+            exit 1
+          }
+
+      # Step 11: Show applied IngressRoutes
+      - name: Show applied IngressRoutes
+        run: |
+          set -euo pipefail
+
+          kubectl get ingressroutes -A
+          # kubectl get ingressroute -n $NAMESPACE
